# ~/.config/starship.toml

add_newline = false

[username]
style_user = "bold cyan"
format = "[$user]($style) ∈ "
show_always = true

[hostname]
format = "[$hostname]($style):"
style = "bold dimmed white"

[directory]
format = "[$path](italic green)[$lock_symbol]($lock_style) "

[character]
success_symbol = "[❯](bold yellow)[❯](bold cyan)[❯](bold purple)"
error_symbol = "[❯](bold bright-red)[❯](bold red)[❯](bold yellow)"
vimcmd_symbol = "[❮](bold yellow)[❮](bold cyan)[❮](bold purple)"

[battery]
full_symbol = "🔋 "
empty_symbol = "💀 "
charging_symbol = "⚡ "
discharging_symbol = "🪫 "

[git_branch]
format = "[$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

#[git_state]
#format = "[\($state( $progress_current of $progress_total)\)]($style) "

[git_status]
style = "bright white"
modified = "δ"
stashed = "🪏"
conflicted = "🙅‍♂️"
# format = "$all_status$head_behind"

[package]
disabled = true

[line_break]
disabled = false

[cmd_duration]
disabled = true

[aws]
disabled = true

[julia]
format = "[$symbol$verion](style)"
style = "bold green"

[golang]
format = "[🐹$version]($style)"

[python]
format = "[🐍$version]($style)"
style = "bold green"

[rust]
format = "[🦀$version]($style)"

[nodejs]
format = "[🤖$version]($style)"
